### ISSUE TITLE
NVR 3.1.5

### ISSUE THREAD

**Issue by mjruotolo** [project802/smartthings#4]
I am running 3.1.5 I have the correct api key and pointing to the correct IP but no cameras show in my smartthings.  Is the api different in in 3.1.5?  I cant upgrade to 3.5 because my camera wont support that firmware.
Thanks
Mike

**Comment by project802** [comment]
Mike, I don't have the ability to test with 3.1.5.  

1 - Did you also install and publish the device handler? 
2 - Do you have any logs from the SmartThings "Live Logging"?  Start the logging, install the SmartApp, paste the logs.

**Comment by project802** [comment]
FYI, 3.1.5 issues are currently being worked in the ST Community thread and the 'bootstrap_refactor' branch.

https://community.smartthings.com/t/ubiquiti-unifi-video-nvr-integration/70161

I hope to have an Aircam here around the end of the week so I can test.

**Comment by project802** [comment]
I will consider this issue closed since I have verified support with 3.1.5 and merged it into master.  Please pull down the latest app and device code.
